/* Automatically generated by configure - do not modify */
//#define ARCH_X86 1
//#define HAVE_MMX 1
#define _MSC_VER 1000
#define CONFIG_DECODERS 1
#define HAVE_MALLOC_H 1
#undef  HAVE_MEMALIGN
#define printf(args...) /**/
#define fprintf(args...) /**/
#define snprintf(args...) /**/

//#ifdef feof(p)
//#undef feof
//#endif

#ifndef M_PI
 #define M_PI 3.14159265358979323846
#endif

